trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureKeyVault@2
  displayName: Get Secrets from Key Vault
  inputs:
    azureSubscription: 'Project2'
    KeyVaultName: 'key-vault-pjt'
    SecretsFilter: '*'
    RunAsPreJob: false
    
- task: CmdLine@2
  displayName: Write Secret into File
  inputs:
    script: |
      echo "SAS-URL before writing to file: $(SAS-URL)"
      echo "$(SAS-URL)" > secret.txt
      echo "Contents of secret.txt:"
      cat secret.txt
      ls -l

- task: CopyFiles@2
  displayName: Copy Secrets File
  inputs:
    Contents: 'secret.txt'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- script: |
    echo "Files in Artifact Staging Directory before publishing:"
    ls -l $(Build.ArtifactStagingDirectory)
  displayName: List Files in Artifact Staging Directory Before Publishing

- task: PublishBuildArtifacts@1
  displayName: Publish Secrets File
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

- script: |
    echo "Files in Artifact Staging Directory after publishing:"
    ls -l $(Build.ArtifactStagingDirectory)
  displayName: List Files in Artifact Staging Directory After Publishing
